import type { Metadata } from "next";
import Link from "next/link";

export const metadata: Metadata = {
  title: "Terms of Service",
  description:
    "DokiDokiTools Terms of Service 窶・the rules governing your use of our free online utility tools. Free for personal and commercial use.",
  alternates: { canonical: "https://dokidokitools.vercel.app/legal/terms" },
  openGraph: {
    title: "Terms of Service | DokiDokiTools",
    description: "DokiDokiTools Terms of Service. Simple, fair, and clear.",
    url: "https://dokidokitools.vercel.app/legal/terms",
    type: "website",
  },
};

const sections = [
  {
    title: "1. Acceptance of Terms",
    content: "By accessing or using DokiDokiTools at dokidokitools.vercel.app, you agree to be bound by these Terms of Service. If you do not agree, you may not use the Site. These Terms apply to all visitors and users.",
  },
  {
    title: "2. Description of Service",
    content: "DokiDokiTools provides free, browser-based utility tools including username generators, word finders, recipe scalers, Japanese text converters, and IP address checkers. All Tools run in your browser. No account is required.",
  },
  {
    title: "3. Permitted Use & Restrictions",
    content: "You may use DokiDokiTools for personal and commercial purposes. You must NOT:",
    bullets: [
      "Violate any applicable law or regulation",
      "Attempt unauthorized access to any part of the Site",
      "Use bots or scrapers to degrade service quality for other users",
      "Decompile or reverse-engineer any software on the Site",
    ],
  },
  {
    title: "4. Intellectual Property",
    content: "The Site and its content are the exclusive property of DokiDokiTools. Output generated by our Tools (usernames, scaled recipes, etc.) belongs to you and may be used freely.",
  },
  {
    title: "5. Disclaimer of Warranties",
    content: 'THE SITE AND ALL TOOLS ARE PROVIDED "AS IS" WITHOUT WARRANTIES OF ANY KIND. WE DO NOT WARRANT THAT THE SERVICE WILL BE UNINTERRUPTED, ERROR-FREE, OR THAT RESULTS WILL BE ACCURATE OR RELIABLE.',
  },
  {
    title: "6. Limitation of Liability",
    content: "TO THE MAXIMUM EXTENT PERMITTED BY LAW, DokiDokiTools SHALL NOT BE LIABLE FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, OR PUNITIVE DAMAGES ARISING FROM YOUR USE OF THE SITE OR TOOLS.",
  },
  {
    title: "7. Advertising",
    content: "DokiDokiTools displays advertisements via Google AdSense to keep our tools free. By consenting to cookies, you acknowledge that ads may be personalized based on your browsing history. See our Privacy Policy for details.",
  },
  {
    title: "8. Governing Law",
    content: "These Terms are governed by applicable law. Any disputes shall be subject to the exclusive jurisdiction of the relevant courts. If any provision of these Terms is found unenforceable, the remaining provisions continue in full effect.",
  },
  {
    title: "9. Changes to Terms",
    content: "We reserve the right to modify these Terms at any time. Changes will be posted with an updated date. Continued use constitutes acceptance of the revised Terms.",
  },
  {
    title: "10. Contact",
    content: "Questions? Email legal@DokiDokiTools.com.",
  },
];

const NAV_STYLE = { backgroundColor: "#6B21A8" } as const;
const PAGE_BG   = { backgroundColor: "#F8F5FF" } as const;
const CARD      = { border: "1.5px solid #EDE9FE" } as const;
const BADGE     = { background: "linear-gradient(135deg,#FF8A00,#FFB347)" } as const;

export default function TermsPage() {
  return (
    <div className="flex flex-col min-h-screen" style={{ ...PAGE_BG, fontFamily: "'Outfit','Inter',sans-serif" }}>

      {/* Nav */}
      <nav style={NAV_STYLE} className="shadow-lg">
        <div className="w-full max-w-6xl mx-auto px-6 flex items-center justify-between" style={{ height: "4.5rem" }}>
          <Link href="/" className="flex items-center gap-3">
            <div className="w-9 h-9 rounded-xl flex items-center justify-center text-white font-black text-lg shadow-md" style={BADGE}>Z</div>
            <span className="text-white font-black text-xl tracking-wide">Zenith<span style={{ color: "#FFB347" }}>Tools</span></span>
          </Link>
          <div className="flex gap-8 text-sm font-semibold text-white/60">
            <Link href="/" className="hover:text-white transition-colors">Home</Link>
            <Link href="/legal/privacy" className="hover:text-white transition-colors">Privacy</Link>
            <Link href="/legal/cookies" className="hover:text-white transition-colors">Cookies</Link>
          </div>
        </div>
      </nav>

      {/* Header */}
      <div style={NAV_STYLE} className="relative overflow-hidden">
        <div className="absolute -top-16 -right-16 w-64 h-64 rounded-full" style={{ background: "radial-gradient(circle,#FF8A00 0%,#FF6B00 45%,transparent 70%)", opacity: 0.6 }} />
        <div className="relative z-10 max-w-6xl mx-auto px-6 py-12">
          <p className="text-white/50 text-sm font-semibold uppercase tracking-widest mb-2">Legal</p>
          <h1 className="text-white font-black text-4xl md:text-5xl" style={{ letterSpacing: "-0.02em" }}>
            Terms of <span style={{ color: "#FFB347" }}>Service</span>
          </h1>
          <p className="text-white/40 text-sm font-medium mt-2">Last Updated: April 22, 2026</p>
        </div>
        <svg viewBox="0 0 1440 32" preserveAspectRatio="none" className="w-full block" style={{ height: 32, fill: "#F8F5FF" }}>
          <path d="M0,32 L0,0 Q360,32 720,16 Q1080,0 1440,24 L1440,32 Z" />
        </svg>
      </div>

      {/* Sections */}
      <main className="flex-grow max-w-4xl mx-auto w-full px-6 py-12 flex flex-col gap-4">
        {sections.map((s, i) => (
          <div key={i} className="bg-white rounded-3xl p-7 shadow-sm" style={CARD}>
            <div className="flex items-center gap-3 mb-3">
              <div className="w-9 h-9 rounded-xl flex items-center justify-center text-white font-black text-xs shadow flex-shrink-0" style={BADGE}>
                {String(i + 1).padStart(2, "0")}
              </div>
              <h2 className="font-black text-lg" style={{ color: "#3B0764" }}>{s.title}</h2>
            </div>
            {s.content && <p className="leading-relaxed font-medium text-sm" style={{ color: "#9B80C0" }}>{s.content}</p>}
            {s.bullets && (
              <ul className="mt-2 space-y-1.5 text-sm font-medium" style={{ color: "#9B80C0" }}>
                {s.bullets.map((b, bi) => (
                  <li key={bi} className="flex items-start gap-2">
                    <span className="mt-1.5 w-1.5 h-1.5 rounded-full flex-shrink-0" style={{ backgroundColor: "#FF8A00" }} />
                    {b}
                  </li>
                ))}
              </ul>
            )}
          </div>
        ))}
      </main>

      <footer style={NAV_STYLE} className="mt-8">
        <div className="max-w-6xl mx-auto px-6 py-10 flex flex-col md:flex-row items-center justify-between gap-4">
          <span className="text-white/30 font-semibold text-sm">&copy; 2026 DokiDokiTools. All rights reserved.</span>
          <div className="flex gap-8 text-sm font-semibold text-white/30">
            <Link href="/" className="hover:text-white transition-colors">Home</Link>
            <Link href="/legal/privacy" className="hover:text-white transition-colors">Privacy</Link>
            <Link href="/legal/cookies" className="hover:text-white transition-colors">Cookies</Link>
          </div>
        </div>
      </footer>
    </div>
  );
}
